### ISSUE TITLE
Debug log messages not displaying on-screen

### ISSUE THREAD

**Issue by techhat** [saltstack/salt-fuse#6]
`salt-fuse /media/salt/ -l debug` does not display any messages, outside of the normal initialization messages:

```
[DEBUG   ] Reading configuration from /etc/salt/fuse
[DEBUG   ] loading log_handlers in ['/var/cache/salt/fuse/extmods/log_handlers', '/usr/lib/python2.7/site-packages/salt/log/handlers']
[DEBUG   ] Skipping /var/cache/salt/fuse/extmods/log_handlers, it is not a directory
```

@s0undt3ch, would you mind taking a look?

**Comment by rallytime** [comment]
This repo is deprecated and the repo is archived. Therefore, this issue is now closed. Thank you.
